### ISSUE TITLE
Add glasbey_tableau10?

### ISSUE THREAD

**Issue by endolith** [holoviz/colorcet#45]
**Is your feature request related to a problem? Please describe.**
I sometimes want to plot lots of colors but I want them to look nice

**Describe the solution you'd like**
Similar to #11, could you add a Glasbey color list that starts with the (new) Tableau 10 series?

![](https://cdnl.tblsft.com/sites/default/files/blog/tableau10_palette.png)

```
4e79a7
f28e2c
e15759
76b7b2
59a14f
edc949
af7aa1
ff9da7
9c755f
bab0ab
```

**Comment by jbednar** [comment]
Sure!  But to clarify first, are you looking for additional colors in the style of NewTableau10 (with medium saturation and medium amounts of gray, from the looks of them)?  Glasbey colors will be the _opposite_, i.e. the next few colors in the series will be maximally _different_ from the NewTableau10 colors,  either unsaturated, highly saturated, with lots of gray mixed in, with no gray mixed in, etc.  If you're after more colors like NewTableau10, you could achieve that with the algorithm, but first you would have to filter out all the colors not in that style, and only then run the algorithm.

**Comment by endolith** [comment]
Good point.  They have pretty contradictory goals, I guess, where Tableau is a bunch of colors of similar lightness that look good together, and Glasbey is just maximally different.  I guess what I really want is an extended version Tableau with 25-30 colors that look good together and are reasonably distinguishable, which maybe I should make myself since it's not as general-purpose.

I was just thinking of this since the old Tableau10 is the beginning of `glasbey_category10`.

**Comment by jbednar** [comment]
Makes sense.  If you were able to constrain the colors available by appropriate options to the underlying glasbey code (which may or may not require modifying the glasbey code) so that it would continue to produce colors in that style, then I'd love to see that and then would add the resulting automatically generated colormap here. But assuming you aren't starting such a project, then I'll close this issue for now, as it sounds like you don't need what I could do myself (glasbey colors different from NewTableau10). 

If you make a new set by hand, you can consider contributing it to https://github.com/pyviz/contrib_colormaps , where hand-constructed maps are fine. I do think others could be interested in such a colormap!
